#include "filter.hpp"
#include "../exceptions/parse_error.hpp"
#include "builtin.hpp"
#include "../player/note.hpp"

std::string Filter_Metadata::ToString() const {
    std::string ret = keyword;
    size_t maxKwdLen = Filter::GetLongestKeywordMeta().keyword.size();
    for(size_t i = 0; i < (maxKwdLen - keyword.size())/8 + 1; i++) {
        ret += '\t';
    }
    ret += (maxKwdLen == keyword.size()?"":"\tSyntax: ") + syntax + "\t" + desc;
    return ret;
}

void Filter::Init() {
    AddMetadata(Filter_Metadata("absolute", AbsoluteValue::Create, "absolute {<src>}", "Takes the absolute value of the sample generated by src"));
    AddMetadata(Filter_Metadata("abs", AbsoluteValue::Create, "abs {<src>}", "Alias to 'absolute'"));
    AddMetadata(Filter_Metadata("add_frequency", AddFrequencyFilter::Create, "add_frequency(<sine_amplitude_curve> <cosine_amplitude_curve> [resolution])", "Adds the specified frequencies to the fft. Phase can be encoded through the differences of the two curves. The curves are (Hz -> amplitude)"));
    AddMetadata(Filter_Metadata("add_freq", AddFrequencyFilter::Create, "add_freq(<sine_amplitude_curve> <cosine_amplitude_curve> [resolution])", "Alias for 'add_frequency'"));
    AddMetadata(Filter_Metadata("bounds", BoundsFilter::Create, "bounds([lower]:[upper]) [{src}]", "Restricts playable notes to have a length of fixed size"));
    AddMetadata(Filter_Metadata("clamp", ClampFilter::Create, "clamp([lower]:[upper]) [{src}]", "Restricts \"src\"'s output to be in the specified range"));
    AddMetadata(Filter_Metadata("copy", CopyReference::Create, "copy(<source index or name>)", "Creates a copy of the referenced filter chain. The coied labels are not exposed!"));
    AddMetadata(Filter_Metadata("delay", DelayFilter::Create, "pass(<freq_resp_curve> [samples]) [{src}]", "Arbitrary pass filter (freq_resp_curve: Interpolated<double>)"));
    AddMetadata(Filter_Metadata("dummy", DummyFilter::Create, "dummy()", "Does nothing"));
    AddMetadata(Filter_Metadata("feedback", Feedback::Create, "feedback(<depth> [fb_filter]) [{src}]", "Sends back signals in the chain by `depth`(uint) after being processed by `fb_filter`(Filterchain)"));
    AddMetadata(Filter_Metadata("gain", GainFilter::Create, "gain(<amount>) [{src}]", "Multiplies the samples coming from src by `amount`(double)"));
    AddMetadata(Filter_Metadata("pass", FFTPass::Create, "pass(<freq_resp_curve> [samples]) [{src}]", "Arbitrary pass filter (freq_resp_curve: Interpolated<double>)"));
    AddMetadata(Filter_Metadata("quantize", QuantizeFilter::Create, "quantize(<bits>) [{src}]", "Quantizes the signal coming from `src` to be `bits`(uint)"));
    AddMetadata(Filter_Metadata("reference", Reference::Create, "reference(<source index or name>)", "Fetches the last sample of the referenced source."));
    AddMetadata(Filter_Metadata("ref", Reference::Create, "ref(<source index or name>)", "Alias to 'reference'."));
    AddMetadata(Filter_Metadata("split", Splitter::Create, "split([f_1] [f_2] ... [f_n]) [{src}]", "Splits the signal into different paths, then combines them. (f_k: Filterchain)"));
    AddMetadata(Filter_Metadata("mockfft", MockFFT::Create, "split([f_1] [f_2] ... [f_n]) [{src}]", "Splits the signal into different paths, then combines them. (f_k: Filterchain)"));
}

void Filter::operator()(double phase, double t, int srate, double note_amplitude) {
    if(src == nullptr) { return; }
    (*src)(phase, t, srate, note_amplitude);
}

void Filter::addNote(std::unique_ptr<Note> note) {
    if(src == nullptr) { return; }
    src->addNote(std::move(note));
}

double Filter::getSample(int samplerate) {
    m_prev_sample = filter(src == nullptr? getAccumulator() : src->getSample(samplerate), 0, 0, 0) + m_feedback;
    return m_prev_sample;
}
double Filter::getSingleSample(double p, double t, int samplerate) {
    return filter(src == nullptr? 0 : src->getSingleSample(p, t, samplerate), 0, 0, 0);
}

std::string Filter::getFormattedMetadata() {
    std::string ret = "";
    for(const Filter_Metadata& f : meta) {
        ret += f.keyword + "\t" + (f.keyword.size() < 8? "\t" : "") + f.syntax + "\t" + f.desc + "\n";
    }
    return ret;
}
void Filter::Write(std::ostream& str) const {
    str << GetNameAndParams();
    if(src != nullptr) {
        str << " {";
        src->Write(str);
        str << "}";
    }
} 
